import Foundation
import CoreData

// MARK: - CoreData Entity Extensions
// Note: These are auto-generated by CoreData, but we provide extensions for convenience

extension WordEntity {
    // Additional helper methods can be added here
}

extension MeaningEntity {
    // Additional helper methods can be added here
}

extension ExampleEntity {
    // Additional helper methods can be added here
}

extension TagEntity {
    // Additional helper methods can be added here
}

extension ReviewLogEntity {
    // Additional helper methods can be added here
}
